export const ADDING_BROKER_DETAIL = 'CHANGE_BROKER_DETAIL'
export const DEFAULT_BROKER_DETAIL = 'DEFAULT_BROKER_DETAIL'
export const DELETE_BROKER = 'DELETE_BROKER'
export const EDIT_BROKER = "EDIT_BROKER"